# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organdb', '0002_auto_20161014_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='region',
        ),
    ]
