# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organdb', '0003_auto_20161014_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('biography', models.TextField()),
                ('born', models.DateField()),
                ('died', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_date', models.DateField()),
                ('key_action', models.CharField(max_length=20)),
                ('stop_action', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('published', models.BooleanField()),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organdb.Builder')),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pedalboard', models.BooleanField()),
                ('min_note', models.CharField(max_length=2)),
                ('max_note', models.CharField(max_length=2)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('born', models.DateField()),
                ('died', models.DateField()),
                ('biography', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organdb.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='recordings/')),
                ('description', models.TextField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organdb.Instrument')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organdb.Performer')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='samples/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('length', models.CharField(max_length=5)),
                ('reed', models.BooleanField()),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organdb.Keyboard')),
            ],
        ),
        migrations.CreateModel(
            name='StopFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StopType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organdb.Builder')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organdb.Instrument')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='region',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organdb.StopType'),
        ),
        migrations.AddField(
            model_name='concert',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organdb.Instrument'),
        ),
    ]
