# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdb', '0004_auto_20161014_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(),
        ),
    ]
