# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organdb', '0005_auto_20161014_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organdb.Concert')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organdb.Performer')),
            ],
        ),
        migrations.CreateModel(
            name='StopMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organdb.StopFamily')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organdb.StopType')),
            ],
        ),
    ]
