# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdb', '0006_performance_stopmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='keyboards',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='pedalboard',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='stops',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
