# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdb', '0009_auto_20161104_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
