# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organdb', '0010_auto_20161104_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='organdb.Location'),
            preserve_default=False,
        ),
    ]
