# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdb', '0012_auto_20161104_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builder',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='died',
            field=models.DateField(blank=True, null=True),
        ),
    ]
