# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organdb', '0017_keyboard_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='stop_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='organdb.StopType'),
            preserve_default=False,
        ),
    ]
