# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdb', '0019_auto_20161104_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='performer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
